#!/usr/bin/env bash
# Generate the self-signed TLS cert + key and embed both as C string literals
# into firmware/src/certs.h for the ESP32 HTTPS server.
#
# Run this ONCE per clone (the output files are .gitignore'd because the
# private key must never be committed to a public repo).
#
# Re-run if you want to rotate the cert or extend its validity.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CERT_DIR="$ROOT/firmware/src/certs"
HEADER="$ROOT/firmware/src/certs.h"

mkdir -p "$CERT_DIR"

# --- Cert parameters (edit SAN list if your local IPs differ) ---
CN="stoveiq.local"
SAN="DNS:stoveiq.local,DNS:*.local,DNS:localhost,IP:192.168.1.183,IP:192.168.4.1,IP:127.0.0.1"
DAYS=3650

openssl req -x509 -nodes \
  -newkey rsa:2048 \
  -keyout "$CERT_DIR/server.key" \
  -out    "$CERT_DIR/server.crt" \
  -days   "$DAYS" \
  -subj   "/CN=$CN/O=StoveIQ Open Source" \
  -addext "subjectAltName=$SAN" \
  >/dev/null 2>&1

chmod 600 "$CERT_DIR/server.key"

# Embed both files as C string literals in certs.h
python3 - <<PY > "$HEADER"
with open("$CERT_DIR/server.crt") as f: crt = f.read()
with open("$CERT_DIR/server.key") as f: key = f.read()
def esc(s):
    return ''.join(
        '"' + line.rstrip('\n').replace('\\\\', '\\\\\\\\').replace('"', '\\\\"') + '\\\\n"\n'
        for line in s.splitlines()
    )
print("/* Auto-generated by scripts/gen-cert.sh. DO NOT EDIT BY HAND. */")
print("/* Re-run gen-cert.sh to regenerate. */")
print("#pragma once")
print()
print("static const char SERVER_CERT_PEM[] =")
print(esc(crt).rstrip() + ";")
print()
print("static const char SERVER_KEY_PEM[] =")
print(esc(key).rstrip() + ";")
PY

echo "Generated:"
echo "  $CERT_DIR/server.crt (public cert)"
echo "  $CERT_DIR/server.key (PRIVATE KEY — do not share)"
echo "  $HEADER (embedded PEM strings consumed by firmware build)"
echo
echo "CN=$CN, valid $DAYS days."
